blank_issues_enabled: false
contact_links:
  - name: GitHub Actions - GitHub Support Community Forum
    url: https://github.community/c/code-to-cloud/github-actions/41
    about: Please ask questions about GitHub Actions here.
  - name: GitHub Pages Documentation
    url: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages
    about: GitHub Pages official documentaion here.
  - name: GitHub Actions Documentation
    url: https://docs.github.com/en/free-pro-team@latest/actions
    about: GitHub Actions official documentation here.
